### ISSUE TITLE
Resize the window

### ISSUE THREAD

**Issue by zyke** [MacIrssi/MacIrssi#25]
Is there a way to resize the window? 
When I try to expand the window so it will fit the whole screen I just get grey edges. Is there a way to make the application follow when you resize it? :)

**Comment by ghost** [comment]
Resizing MacIrssi works fine for me; can you provide steps to reproduce the problem you are seeing?

**Comment by zyke** [comment]
Basically I just use the mouse pointer to select the lower right corner and drag the window out so it gets bigger, but all I get is a gray area around the original MacIrssi.
I am not at home right now, when I get home I could provide a picture :)

**Comment by ghost** [comment]
Sure, can you also check what version you are running. This definitely works for me on 0.8.6.6 (and on develop HEAD too).

**Comment by zyke** [comment]
picture: http://i54.tinypic.com/kb97dh.png
version: 0.8.6.6 (Build 2e2f6aa)

What I did was that I pressed the green button in the top left corner, and that was what happened.

**Comment by ghost** [comment]
I cannot reproduce this with the latest development build. Please feel free to download it and try and reproduce on there. If it doesn't reproduce, consider it already fixed by accident ;).

https://github.com/daagaak/MacIrssi/downloads

**Comment by zyke** [comment]
I found the source to the problem.

go into Preferences - Apperance. Chose "Display channels vertically on the left"
then restart macirssi, now you should get the grey area. I changed the channel list to "at the top" and resized it, that was no problem at all, then I changed back to "on the left" and now I only got a small grey area at the top. However... I lost the "text bar" where I type.. so well yeah.. haha :P

**Comment by ghost** [comment]
Ok, yep. I see that. Things get über messed up on my end if I switch between styles. Guess I need to work on that. I'll let you know when I have something solid fixed.

**Comment by ghost** [comment]
Fixed in 3eb02b894c601de7304fdb7837925c5dccfd88ca, you'll see it in the next beta build.

**Comment by zyke** [comment]
I'll be looking forward to it :)
thanks daagaak

**Comment by ghost** [comment]
Just uploaded.

**Comment by zyke** [comment]
will be sure to check it out when I get home : )

**Comment by anders** [comment]
I still get this using 0.8.6.6 (Build 2e2f6aa), I also have the channel list to the left.
